import React from 'react';
import { InterviewAnalysis, AssessmentCategory } from '../types';
import { 
  CheckCircle2, 
  AlertTriangle, 
  Lightbulb, 
  BarChart3, 
  User, 
  Mic, 
  MonitorPlay,
  ArrowRight
} from 'lucide-react';
import {
  ResponsiveContainer,
  RadialBarChart,
  RadialBar,
  PolarAngleAxis
} from 'recharts';

interface AnalysisResultProps {
  analysis: InterviewAnalysis;
  onReset: () => void;
}

const ScoreBadge: React.FC<{ score: number }> = ({ score }) => {
  let colorClass = 'text-red-500 bg-red-50 border-red-200';
  if (score >= 80) colorClass = 'text-green-600 bg-green-50 border-green-200';
  else if (score >= 60) colorClass = 'text-amber-600 bg-amber-50 border-amber-200';

  return (
    <div className={`flex items-center justify-center w-12 h-12 rounded-full border-2 font-bold text-lg ${colorClass}`}>
      {score}
    </div>
  );
};

const CategoryCard: React.FC<{ category: AssessmentCategory }> = ({ category }) => {
  const getIcon = (name: string) => {
    const n = name.toLowerCase();
    if (n.includes('verbal')) return <Mic className="w-5 h-5" />;
    if (n.includes('screen') || n.includes('visual')) return <MonitorPlay className="w-5 h-5" />;
    if (n.includes('body') || n.includes('non-verbal')) return <User className="w-5 h-5" />;
    return <BarChart3 className="w-5 h-5" />;
  };

  return (
    <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-sm hover:shadow-md transition-shadow">
      <div className="flex justify-between items-start mb-3">
        <div className="flex items-center space-x-2 text-slate-700 font-semibold">
          <div className="p-2 bg-slate-100 rounded-lg">
            {getIcon(category.name)}
          </div>
          <span>{category.name}</span>
        </div>
        <ScoreBadge score={category.score} />
      </div>
      <p className="text-slate-600 text-sm leading-relaxed">
        {category.feedback}
      </p>
    </div>
  );
};

export const AnalysisResult: React.FC<AnalysisResultProps> = ({ analysis, onReset }) => {
  const chartData = [
    { name: 'Score', value: analysis.overallScore, fill: '#4f46e5' }
  ];

  return (
    <div className="max-w-5xl mx-auto pb-12 animate-fade-in">
      
      {/* Header Section */}
      <div className="flex flex-col md:flex-row justify-between items-end mb-8 gap-4">
        <div>
          <h2 className="text-3xl font-bold text-slate-900">Analysis Report</h2>
          <p className="text-slate-500 mt-1">Generated by Gemini 2.5 Flash</p>
        </div>
        <button 
          onClick={onReset}
          className="px-6 py-2.5 bg-slate-900 text-white rounded-lg hover:bg-slate-800 transition-colors font-medium text-sm flex items-center"
        >
          Analyze Another Video
        </button>
      </div>

      {/* Overview Card */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        {/* Score Chart */}
        <div className="col-span-1 bg-white p-6 rounded-2xl border border-slate-200 shadow-sm flex flex-col items-center justify-center relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-1 bg-indigo-500"></div>
          <h3 className="text-slate-500 font-medium mb-4 uppercase tracking-wider text-xs">Overall Performance</h3>
          <div className="w-48 h-48 relative">
            <ResponsiveContainer width="100%" height="100%">
              <RadialBarChart 
                innerRadius="80%" 
                outerRadius="100%" 
                barSize={10} 
                data={chartData} 
                startAngle={90} 
                endAngle={-270}
              >
                <PolarAngleAxis type="number" domain={[0, 100]} angleAxisId={0} tick={false} />
                <RadialBar
                  background
                  dataKey="value"
                  cornerRadius={30 / 2}
                  fill="#4f46e5"
                />
              </RadialBarChart>
            </ResponsiveContainer>
            <div className="absolute inset-0 flex flex-col items-center justify-center">
              <span className="text-4xl font-bold text-slate-900">{analysis.overallScore}</span>
              <span className="text-sm text-slate-400">/ 100</span>
            </div>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="col-span-1 md:col-span-2 bg-indigo-600 p-8 rounded-2xl shadow-lg text-white flex flex-col justify-center">
          <h3 className="text-indigo-100 font-medium mb-2 uppercase tracking-wider text-xs flex items-center gap-2">
            <Lightbulb className="w-4 h-4" /> Executive Summary
          </h3>
          <p className="text-lg leading-relaxed font-light">
            "{analysis.summary}"
          </p>
        </div>
      </div>

      {/* Category Grid */}
      <h3 className="text-xl font-bold text-slate-800 mb-4 px-1">Detailed Breakdown</h3>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-6 mb-10">
        {analysis.categories.map((cat, idx) => (
          <CategoryCard key={idx} category={cat} />
        ))}
      </div>

      {/* Strengths & Weaknesses */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-10">
        <div className="bg-green-50 p-6 rounded-2xl border border-green-100">
          <h4 className="flex items-center gap-2 text-green-800 font-bold mb-4 text-lg">
            <CheckCircle2 className="w-5 h-5" />
            Key Strengths
          </h4>
          <ul className="space-y-3">
            {analysis.strengths.map((item, i) => (
              <li key={i} className="flex items-start gap-3 text-green-900/80 text-sm">
                <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-green-500 shrink-0"></span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="bg-amber-50 p-6 rounded-2xl border border-amber-100">
          <h4 className="flex items-center gap-2 text-amber-800 font-bold mb-4 text-lg">
            <AlertTriangle className="w-5 h-5" />
            Areas for Improvement
          </h4>
          <ul className="space-y-3">
            {analysis.weaknesses.map((item, i) => (
              <li key={i} className="flex items-start gap-3 text-amber-900/80 text-sm">
                <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-amber-500 shrink-0"></span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Actionable Tips */}
      <div className="bg-white rounded-2xl p-8 border border-slate-200 shadow-sm">
        <h3 className="text-xl font-bold text-slate-800 mb-6 flex items-center gap-2">
          <ArrowRight className="w-6 h-6 text-indigo-600" />
          Recommended Actions
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {analysis.actionableTips.map((tip, idx) => (
            <div key={idx} className="bg-slate-50 p-5 rounded-xl border border-slate-100 relative">
              <span className="absolute -top-3 -left-3 w-8 h-8 flex items-center justify-center bg-indigo-600 text-white font-bold rounded-lg text-sm shadow-md">
                {idx + 1}
              </span>
              <p className="text-slate-700 text-sm font-medium mt-1">
                {tip}
              </p>
            </div>
          ))}
        </div>
      </div>

    </div>
  );
};
